---
- name: Copy ipsec configuration in place.
  copy:
    src: ipsec.{{ ansible_os_family }}.conf
    dest: /etc/ipsec.conf
    mode: 00600
  notify:
    - restart vpn-server

- name: Copy pre-shared-key in place.
  template:
    src: default.secrets.j2
    dest: /etc/ipsec.secrets
    mode: 00600
  notify:
    - restart vpn-server
