---
# install
- name: Ensure l2tp-ipsec server packages are installed.
  yum:
    name: "{{ item }}"
    state: installed
    enablerepo: epel
  with_items:
    - xl2tpd
    - libreswan
    - lsof

# configure ipsec
- name: Copy ipsec configuration in place.
  copy:
    src: ipsec.conf
    dest: /etc/ipsec.conf
    mode: 00600
  notify:
    - restart vpn-server

- name: Copy pre-shared-key in place.
  template:
    src: default.secrets.j2
    dest: /etc/ipsec.d/default.secrets
    mode: 00600
  notify:
    - restart vpn-server

- name: Copy pre-shared-key in place.
  template:
    src: l2tp-ipsec.conf.j2
    dest: /etc/ipsec.d/l2tp-ipsec.conf
    mode: 00600
  notify:
    - restart vpn-server

- name: Copy credential file in place.
  template:
    src: chap-secrets.j2
    dest: /etc/ppp/chap-secrets
    mode: 00600
  notify:
    - restart vpn-server

# configure xltpd
- name: Copy xl2tpd config file in place.
  template:
    src: xl2tpd.conf.j2
    dest: /etc/xl2tpd/xl2tpd.conf
    mode: 00600
  notify:
    - restart vpn-server

- name: Copy credential file in place.
  template:
    src: xl2tpd.conf.j2
    dest: /etc/xl2tpd/xl2tpd.conf
    mode: 00600
  notify:
    - restart vpn-server

# sysctl
- name: Copy sysctl parameter in place.
  template:
    src: sysctl-params.conf.j2
    dest: /etc/sysctl.d/60-vpn-server.conf
  notify:
    - update sysctl

# service
- name: Ensure xl2tpd is started and enabled to start at boot.
  service: name=xl2tpd state=started enabled=yes

- name: Ensure ipsec is started and enabled to start at boot.
  service: name=ipsec state=started enabled=yes
