---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"

# Configure tasks.
- include_tasks: "configure-{{ ansible_os_family }}.yml"

- name: Copy credential file in place.
  template:
    src: chap-secrets.j2
    dest: /etc/ppp/chap-secrets
    mode: 00600
  notify:
    - restart vpn-server

# Configure xl2tpd tasks.
- name: Copy xl2tpd config file in place.
  template:
    src: xl2tpd.conf.j2
    dest: /etc/xl2tpd/xl2tpd.conf
    mode: 00600
  notify:
    - restart vpn-server

- name: Copy xl2tpd option file in place.
  template:
    src: options.xl2tpd.{{ ansible_os_family }}.j2
    dest: /etc/ppp/options.xl2tpd
    mode: 00600
  notify:
    - restart vpn-server

# Setup sysctl tasks.
- name: Copy sysctl parameter in place.
  template:
    src: sysctl-params.conf.j2
    dest: /etc/sysctl.d/60-vpn-server.conf
  notify:
    - update sysctl

# Configure service tasks.
- name: Ensure xl2tpd is started and enabled to start at boot.
  service: name=xl2tpd state=started enabled=yes

- name: Ensure ipsec is started and enabled to start at boot.
  service: name=ipsec state=started enabled=yes

# Setup/install firewall tasks.
- include_tasks: "firewall-{{ ansible_os_family }}.yml"
