---
# install
- name: Ensure l2tp-ipsec server packages are installed.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - xl2tpd
    - strongswan

# configure ipsec
- name: Copy ipsec configuration in place.
  copy:
    src: ipsec.ubuntu.conf
    dest: /etc/ipsec.conf
    mode: 00600
  notify:
    - restart vpn-server

- name: Copy pre-shared-key in place.
  template:
    src: default.secrets.j2
    dest: /etc/ipsec.secrets
    mode: 00600
  notify:
    - restart vpn-server

- name: Copy credential file in place.
  template:
    src: chap-secrets.j2
    dest: /etc/ppp/chap-secrets
    mode: 00600
  notify:
    - restart vpn-server

# configure xltpd
- name: Copy xl2tpd config file in place.
  template:
    src: xl2tpd.conf.ubuntu.j2
    dest: /etc/xl2tpd/xl2tpd.conf
    mode: 00600
  notify:
    - restart vpn-server

- name: Copy xl2tpd option file in place.
  template:
    src: options.xl2tpd.j2
    dest: /etc/ppp/options.xl2tpd
    mode: 00600
  notify:
    - restart vpn-server

# sysctl
- name: Copy sysctl parameter in place.
  template:
    src: sysctl-params.conf.j2
    dest: /etc/sysctl.d/60-vpn-server.conf
  notify:
    - update sysctl

# service
- name: Ensure xl2tpd is started and enabled to start at boot.
  service: name=xl2tpd state=started enabled=yes

- name: Ensure ipsec is started and enabled to start at boot.
  service: name=ipsec state=started enabled=yes

# Firewall
- name: Enable UFW
  ufw:
    state: enabled

- name: Allow all access to udp port
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  with_items: "{{ l2tp_ipsec_server_udp_ports }}"

- name: firewall masquerade
  blockinfile:
    dest: /etc/ufw/before.rules
    insertafter: '^COMMIT\n'
    content: |
      *nat
      -A POSTROUTING -s 0.0.0.0/0 -o {{ l2tp_ipsec_server_bind_interface }} -j MASQUERADE
      COMMIT
  notify:
    - restart ufw

- name: IP forwarding
  lineinfile:
    path: /etc/default/ufw
    regexp: '^DEFAULT_FORWARD_POLICY='
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'
  notify:
    - restart ufw