---
- name: restart vpn-server
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - ipsec
    - xl2tpd

- name: update sysctl
  command: sysctl -p /etc/sysctl.d/60-vpn-server.conf

- name: restart ufw
  service:
    name: ufw
    state: restarted